plugin: google.cloud.gcp_compute
projects:
  - your_project_name
auth_kind: serviceaccount
service_account_file: "./service-account.json"

filters:
  - status = RUNNING
  - labels.managed_by = terraform

groups:
  monitored_servers: true
