- name: Deploy Monitoring Agent
  hosts: monitored_servers
  become: true
  tasks:
    - name: Make monitor dir if not exist
      ansible.builtin.file:
        path: "{{ monitor_dir }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Install RedHat package dependencies
      ansible.builtin.command:
        argv:
          - dnf
          - install
          - -y
          - "{{ item }}"
      loop: "{{ monitor_os_packages.RedHat }}"
      changed_when: false
      when: ansible_os_family == "RedHat"

    - name: Update Debian package cache
      ansible.builtin.command:
        argv:
          - apt-get
          - update
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Install Debian package dependencies
      ansible.builtin.command:
        argv:
          - apt-get
          - install
          - -y
          - "{{ item }}"
      loop: "{{ monitor_os_packages.Debian }}"
      changed_when: false
      when: ansible_os_family == "Debian"

    - name: Copy files to monitor dir
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "{{ monitor_dir }}"
        owner: root
        group: root
        mode: "0644"
      loop:
        - agent.py
        - collectors.py
        - aggregator.py
        - logger.py
        - requirements.txt
      notify: Restart monitor agent

    - name: Create venv and install requirements.txt
      ansible.builtin.pip:
        requirements: "{{ monitor_dir }}/requirements.txt"
        virtualenv: "{{ monitor_dir }}/venv"
        virtualenv_command: "{{ ansible_python_interpreter }} -m venv"
      notify: Restart monitor agent

    - name: Copy service file
      ansible.builtin.copy:
        src: files/monitor-agent.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: "0644"
      notify: Restart monitor agent

  handlers:
    - name: Restart monitor agent
      ansible.builtin.systemd:
        name: monitor-agent
        state: restarted
        enabled: true
        daemon_reload: true
