- name: Install Python for Ansible
  hosts: monitored_servers
  gather_facts: false
  tasks:
    - name: Install python3
      ansible.builtin.raw: |
        if command -v dnf >/dev/null 2>&1; then
          sudo dnf clean packages
          sudo dnf install -y python3.12
        elif command -v apt-get >/dev/null 2>&1; then
          sudo apt-get update && sudo apt-get install -y python3
        fi
      changed_when: false
